---
- name: Force hdmi mode
  lineinfile:
    dest: "{{ raspi_boot_config }}"
    regexp: "hdmi_safe"
    line: "hdmi_safe=1"
    state: present
  when: raspi_force_hdmi

- name: Force hdmi hotplug
  lineinfile:
    dest: "{{ raspi_boot_config }}"
    regexp: "hdmi_force_hotplug"
    line: "hdmi_force_hotplug=1"
    state: present
  when: raspi_force_hdmi_hotplug

- name: Set HDMI group
  lineinfile:
    dest: "{{ raspi_boot_config }}"
    regexp: "hdmi_group"
    line: "hdmi_group={{ raspi_hdmi_group }}"
    state: present

- name: Set HDMI mode
  lineinfile:
    dest: "{{ raspi_boot_config }}"
    regexp: "hdmi_mode"
    line: "hdmi_mode={{ raspi_hdmi_mode }}"
    state: present

- name: Set output rotation
  lineinfile:
    dest: "{{ raspi_boot_config }}"
    regexp: "display_rotate"
    line: "display_rotate={{ raspi_display_rotate }}"
    state: present

- name: Set audio output
  lineinfile:
    dest: "{{ raspi_boot_config }}"
    regexp: "hdmi_drive"
    line: "hdmi_drive={{ raspi_hdmi_drive }}"
    state: present

- name: Set overscan
  lineinfile:
    dest: "{{ raspi_boot_config }}"
    regexp: "disable_overscan"
    line: "disable_overscan={% if raspi_disable_overscan %}1{% else %}0{% endif %}"
    state: present
